name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    -
      name: Checkout version
      uses: actions/checkout@v3

    -
      name: Log in to docker registry
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

    - name: Build the Docker image
      run: docker-compose --file docker-compose.yml -p my-image-name:$(date +%s) build

    -
      name: Push the Docker image to the registry
      run: docker-compose --file docker-compose.yml -p ${{ secrets.DOCKERHUB_USERNAME }}/my-image-name:$(date +%s) push

