name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - ".github/**"

  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    -
      name: Checkout version
      uses: actions/checkout@v3

    -
      name: Log in to docker registry
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

    - name: Build Frontend image
      run: docker build --tag ${{ secrets.DOCKERHUB_USERNAME }}/capacitacaofront:latest ./capacitacao-docker-front

    - name: Build Backend image
      run: docker build --tag ${{ secrets.DOCKERHUB_USERNAME }}/capacitacaoback:latest --file ././capacitacaoDocker/capacitacaoDocker/Dockerfile ./capacitacaoDocker

    -
      name: Push backend to dockerhub
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/capacitacaoback:latest

    -
      name: Push frontend to dockerhub
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/capacitacaofront:latest

