name: Push new Docker versions

on:
  push:
    tags: ['*']


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    -
      name: Checkout version
      uses: actions/checkout@v3

    -
      name: Log in to docker registry
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

    - name: Build Frontend image
      run: docker build --tag ${{ secrets.DOCKERHUB_USERNAME }}/capacitacaofront:${GITHUB_REF#refs/*/} ./capacitacao-docker-front
      with:
        cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/capacitacaofront:buildcache
        cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/capacitacaofront:buildcache,mode=max

    - name: Build Backend image
      run: docker build --tag ${{ secrets.DOCKERHUB_USERNAME }}/capacitacaoback:${GITHUB_REF#refs/*/} --file ././capacitacaoDocker/capacitacaoDocker/Dockerfile ./capacitacaoDocker
      with:
        cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/capacitacaofront:buildcache
        cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/capacitacaofront:buildcache,mode=max

    -
      name: Push backend to dockerhub
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/capacitacaoback:${GITHUB_REF#refs/*/}
