name: Push new Docker versions

on:
  push:
    tags: ['*']


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    -
      name: Checkout version
      uses: actions/checkout@v3

    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

    -
      name: Log in to docker registry
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./capacitacao-docker-front
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/capacitacaofront:${{ env.RELEASE_VERSION }}
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/capacitacaofront:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/capacitacaofront:buildcache,mode=max

    -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./capacitacaoDocker
          file: ./capacitacaoDocker/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/capacitacaoback:${{ env.RELEASE_VERSION }}
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/capacitacaoback:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/capacitacaoback:buildcache,mode=max
